# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mypyqgis.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 837)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, 4, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerTreeWidget = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerTreeWidget.sizePolicy().hasHeightForWidth())
        self.layerTreeWidget.setSizePolicy(sizePolicy)
        self.layerTreeWidget.setMinimumSize(QtCore.QSize(300, 471))
        self.layerTreeWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.layerTreeWidget.setObjectName("layerTreeWidget")
        self.verticalLayout.addWidget(self.layerTreeWidget)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.mapWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapWidget.sizePolicy().hasHeightForWidth())
        self.mapWidget.setSizePolicy(sizePolicy)
        self.mapWidget.setStyleSheet("border: 0.5px solid rgb(52,72,161);\n"
"margin-top:7px;")
        self.mapWidget.setObjectName("mapWidget")
        self.gridLayout.addWidget(self.mapWidget, 0, 1, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 29))
        self.menubar.setMinimumSize(QtCore.QSize(0, 0))
        self.menubar.setSizeIncrement(QtCore.QSize(0, 0))
        self.menubar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu3 = QtWidgets.QMenu(self.menubar)
        self.menu3.setObjectName("menu3")
        self.menu4 = QtWidgets.QMenu(self.menubar)
        self.menu4.setObjectName("menu4")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setCheckable(True)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionzoom_in = QtWidgets.QAction(MainWindow)
        self.actionzoom_in.setObjectName("actionzoom_in")
        self.actionzoom_out = QtWidgets.QAction(MainWindow)
        self.actionzoom_out.setObjectName("actionzoom_out")
        self.actionfull_extent = QtWidgets.QAction(MainWindow)
        self.actionfull_extent.setObjectName("actionfull_extent")
        self.actionpan = QtWidgets.QAction(MainWindow)
        self.actionpan.setObjectName("actionpan")
        self.mapdecoration = QtWidgets.QAction(MainWindow)
        self.mapdecoration.setCheckable(True)
        self.mapdecoration.setObjectName("mapdecoration")
        self.actionstand = QtWidgets.QAction(MainWindow)
        self.actionstand.setObjectName("actionstand")
        self.actionAqua = QtWidgets.QAction(MainWindow)
        self.actionAqua.setObjectName("actionAqua")
        self.actionConsoleStule = QtWidgets.QAction(MainWindow)
        self.actionConsoleStule.setObjectName("actionConsoleStule")
        self.actionElegantDark = QtWidgets.QAction(MainWindow)
        self.actionElegantDark.setObjectName("actionElegantDark")
        self.actionManjaroMix = QtWidgets.QAction(MainWindow)
        self.actionManjaroMix.setObjectName("actionManjaroMix")
        self.actionMaterialDark = QtWidgets.QAction(MainWindow)
        self.actionMaterialDark.setObjectName("actionMaterialDark")
        self.actionUbuntu = QtWidgets.QAction(MainWindow)
        self.actionUbuntu.setObjectName("actionUbuntu")
        self.action_KMeans = QtWidgets.QAction(MainWindow)
        self.action_KMeans.setObjectName("action_KMeans")
        self.action_MeanShift = QtWidgets.QAction(MainWindow)
        self.action_MeanShift.setObjectName("action_MeanShift")
        self.action_DBScan = QtWidgets.QAction(MainWindow)
        self.action_DBScan.setObjectName("action_DBScan")
        self.action_band_synthesis = QtWidgets.QAction(MainWindow)
        self.action_band_synthesis.setObjectName("action_band_synthesis")
        self.action_select = QtWidgets.QAction(MainWindow)
        self.action_select.setObjectName("action_select")
        self.menu.addAction(self.actionopen_file)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionzoom_in)
        self.menu_2.addAction(self.actionzoom_out)
        self.menu_2.addAction(self.actionfull_extent)
        self.menu_2.addAction(self.actionpan)
        self.menu3.addAction(self.actionstand)
        self.menu3.addAction(self.actionAqua)
        self.menu3.addAction(self.actionConsoleStule)
        self.menu3.addAction(self.actionElegantDark)
        self.menu3.addAction(self.actionManjaroMix)
        self.menu3.addAction(self.actionMaterialDark)
        self.menu3.addAction(self.actionUbuntu)
        self.menu4.addAction(self.mapdecoration)
        self.menu4.addAction(self.action_band_synthesis)
        self.menu_3.addAction(self.action_KMeans)
        self.menu_3.addAction(self.action_MeanShift)
        self.menu_3.addAction(self.action_DBScan)
        self.menu_4.addAction(self.action_select)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu3.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "图层管理器"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "操作"))
        self.menu3.setTitle(_translate("MainWindow", "窗体风格"))
        self.menu4.setTitle(_translate("MainWindow", "其他功能"))
        self.menu_3.setTitle(_translate("MainWindow", "非监督分类"))
        self.menu_4.setTitle(_translate("MainWindow", "监督分类"))
        self.actionopen_file.setText(_translate("MainWindow", "打开文件"))
        self.actionsave.setText(_translate("MainWindow", "保存文件"))
        self.actionzoom_in.setText(_translate("MainWindow", "缩小"))
        self.actionzoom_out.setText(_translate("MainWindow", "放大"))
        self.actionfull_extent.setText(_translate("MainWindow", "缩放至图层"))
        self.actionpan.setText(_translate("MainWindow", "漫游"))
        self.mapdecoration.setText(_translate("MainWindow", "地图整饰"))
        self.actionstand.setText(_translate("MainWindow", "系统标准风格"))
        self.actionAqua.setText(_translate("MainWindow", "Aqua"))
        self.actionConsoleStule.setText(_translate("MainWindow", "ConsoleStule"))
        self.actionElegantDark.setText(_translate("MainWindow", "ElegantDark"))
        self.actionManjaroMix.setText(_translate("MainWindow", "ManjaroMix"))
        self.actionMaterialDark.setText(_translate("MainWindow", "MaterialDark"))
        self.actionUbuntu.setText(_translate("MainWindow", "Ubuntu"))
        self.action_KMeans.setText(_translate("MainWindow", "K-Means"))
        self.action_MeanShift.setText(_translate("MainWindow", "MeanShift"))
        self.action_DBScan.setText(_translate("MainWindow", "DBScan"))
        self.action_band_synthesis.setText(_translate("MainWindow", "波段组合"))
        self.action_select.setText(_translate("MainWindow", "监督分类"))
